[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
build_flags =
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -I ../shared
; Core must provide USBHIDGamepad. Standard Espressif32 Arduino core 2.x has it.
